version = 0.1

[default.build.parameters]
cached = true

# sam deploy
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "SiteMonitor-Dev"
region = "ap-northeast-1"
s3_bucket = "example-sam-ap-northeast-1"
s3_prefix = "SiteMonitor-Dev"
confirm_changeset = false
disable_rollback = false
parameter_overrides = [
    "StackName=SiteMonitor-Dev",
    "ProjectName=site-monitor",
    "LogLevel=DEBUG",
    "SubDomain=site-monitor-dev",
    "AllowedIpAddresses=203.0.113.1",
    "HostedZoneId=ZXXXXXXXXXXXXX",
    "AcmCertificateArn=arn:aws:acm:us-east-1:123456789012:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "OsasiPowertoolsPython=arn:aws:lambda:ap-northeast-1:123456789012:layer:OsasiPowertoolsPython:79",
]

# sam deploy --config-env production
[production.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "SiteMonitor"
region = "ap-northeast-1"
s3_bucket = "example-sam-ap-northeast-1"
s3_prefix = "SiteMonitor"
confirm_changeset = true
disable_rollback = false
parameter_overrides = [
    "StackName=SiteMonitor",
    "ProjectName=site-monitor",
    "LogLevel=INFO",
    "SubDomain=site-monitor",
    "AllowedIpAddresses=203.0.113.1",
    "HostedZoneId=ZXXXXXXXXXXXXX",
    "AcmCertificateArn=arn:aws:acm:us-east-1:123456789012:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "OsasiPowertoolsPython=arn:aws:lambda:ap-northeast-1:123456789012:layer:OsasiPowertoolsPython:79",
]
