version = 0.1

# sam deploy
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
stack_name = "SiteMonitor-SES"
region = "us-west-2"
s3_bucket = "example-company-sam-us-west-2"
s3_prefix = "SiteMonitor-SES"
parameter_overrides = [
    "StackName=SiteMonitor-SES",
    "EmailDomain=alive.example-cloud.com",
    "HostedZoneId=ZXXXXXXXXXXXXX",
]
